# Generated by Django 4.2.1 on 2025-05-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('short_description', models.TextField()),
                ('description', models.JSONField()),
                ('tech_skills', models.JSONField()),
                ('strong_words', models.JSONField()),
                ('type', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
