# Generated by Django 4.2.1 on 2025-05-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('visit_count', models.PositiveIntegerField(default=1)),
                ('last_visited', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
